### ISSUE TITLE
Handling gsSPLine3D from Mario Kart 64

### ISSUE THREAD

**Issue by mkst** [glankk/n64#16]
mk64 uses gsSPLine3D (0xB5):

```
00002b00: 0400 81ff 0600 0000 b500 0000 0600 0204  ................
00002b10: b500 0000 0008 0a02 b500 0000 0e06 040c  ................
00002b20: b500 0000 0810 120a b500 0000 1014 1612  ................
00002b30: b500 0000 1418 1a16 b500 0000 1e0e 0c1c  ................
00002b40: b500 0000 2620 2224 b500 0000 2028 2a22  ....& "$.... (*"
00002b50: b500 0000 2e26 242c b500 0000 3630 3234  .....&$,....6024
00002b60: b500 0000 3038 3a32 b500 0000 381e 1c3a  ....08:2....8..:
```
but these are parsed out as (0, 0, 0)

```
$HOME/github/n64/src/gfxdis/gfxdis.f3dex -d 0400 81ff 0600 0000 b500 0000 0600 0204 b500 0000 0008 0a02 b500 0000 0e06 040c
{
    gsSPVertex(0x06000000, 32, 0),
    gsSPLine3D(0, 0, 0),
    gsSPLine3D(0, 0, 0),
    gsSPLine3D(0, 0, 0),
}
```

Is there a way to coerce them into their correct values via gfxdis?

**Comment by glankk** [comment]
This is a bug in `gfxdis.f3dex` and gbi.h with `-DF3DEX_GBI`. A similar issue for SP1Triangle (#15) has been fixed, but is still present for SPLine3D.

**Comment by MegaMech** [comment]
Thank you so much! Just saved me a tonne of work.

**Comment by MegaMech** [comment]
I don't think this issue is resolved.
Original rom:
`B5 00 00 00 06 00 0A 08`
Compile:
`B5 00 00 00 00 0A 08 00`
Gfxdis:
`gsSPLine3D(0, 5, 0),`

Matching implementation:
`mk_Spline3D(6, 0, 10, 8)`

mk_gbi.h (hack for matching):
```
#define __mk_gsSPLine3D_w1f(v0, v1, v2, v3)		            	\
     (_SHIFTR((v3), 0,8)|_SHIFTL((v2), 8, 8)|	                  	\
     _SHIFTL((v1), 16, 8)|_SHIFTL((v0), 24, 8))

#define mk_Line3D(v0, v1, v2, v3)				            	\
{{								                  	\
	_SHIFTL(G_LINE3D, 24, 8)|0,                                 	\
	__mk_gsSPLine3D_w1f(v0, v1, v2, v3)			           		\
}}
```

It's suspected that mk64 used an older version of gbi.h. It's possible that there's nothing wrong with Line3D and mk is just different.

Also, is it possible to get gfxdis to continue reading the next DL after `gsSPEndDisplayList()`?

**Comment by glankk** [comment]
That's weird, I've never seen any G_LINE3D variant that takes four vertices, so that might very well be an old or custom version of F3DEX. If this line command is documented somewhere, it might be appropriate to include it in gfxdis.f3dexb and gbi.h when `-DF3DEX_GBI -DF3D_BETA` is used.
gfxdis does not support continuing after `SPEndDisplayList` or `SPBranchList` at the moment.

**Comment by MegaMech** [comment]
Is it possible to do a temp patch? It would really help. I suspect it uses quadrangle.

The only place may be documented. Is in the leaks. And I aint going anywhere near that.
