### ISSUE TITLE
install-toolchain troubles

### ISSUE THREAD

**Issue by quetzalsly** [glankk/n64#2]
I can't install the toolchain because of a number of problems.

1) If you append the --enable-vc and --enable-static-executables, the binutils version fails to be set causing wget to fail.

2) wget fails saying the certificate is self signed, mentions its kaspersky one (my antivirus), had to disable encrypted connection scanning in its options to fix that one, don't know whats up with all that.

3) Why does the installation take 2 hours? do we really need all this stuff? and right at the end I was greeted by a nice error and a kaspersky blocking a file xgcc.exe saying its a trojan bitcoin miner. Kaspersky never gave me false positives before, its always been great at finding actual viruses so I don't really know what to do about this situation.

Is there any way to install a slim version of this whole toolchain? do we really need 3+ gb of stuff and 2 hours wait every time we install this on a new machine?

**Comment by glankk** [comment]
It seems most of your issues are caused by your antivirus, to which the only advice I can give is to temporarily disable it. Self-signed certificates (which Kaspersky uses for its encryption) is a legitimate security concern, which is why wget refuses to accept them. This is probably the reason why the binutils version check fails as well. `xgcc` is a normal component of the gcc build, but you will have to use your own judgement to decide whether or not to trust the gcc source code.

The toolchain building process requires a lot of disk space, but the finished installation should not take up more than 1GB (note that `--enable-static-executables` increases the size of all executables). To speed up the build, I suggest passing the `-j` option to make (but be aware that this will consume a lot of working memory). Still, compiling on Windows is known to be very slow in general.

**Comment by quetzalsly** [comment]
Tried it again and no problems this time, seems either kaspersky or gcc was updated. Closing issue, thanks.
